name: maria

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - sql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - sql-network

networks:
  sql-network:
    driver: bridge